# -*- mode: python ; coding: utf-8 -*-

import os

block_cipher = None
BASE_DIR = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    [os.path.join(BASE_DIR, 'main.py')],
    pathex=[BASE_DIR],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('database/create_db.py', 'database'),
        ('database/seed.py', 'database'),
        ('database/connection.py', 'database'),
        ('VERSION', '.'),
        ('setup_red.bat', '.'),
        # config.ini NO se empaqueta fijo: se genera por setup_red.bat / installer según cada PC
        # ('config.ini', '.'),  # se deja como ejemplo si existe
    ],
    hiddenimports=[
        'customtkinter',
        'PIL',
        'openpyxl',
        'reportlab',
        'bcrypt',
        'pandas',
        'numpy',
        'matplotlib',
        'matplotlib.backends.backend_tkagg',
        'tkinter',
        'database.create_db',
        'database.seed',
        'database.connection',
        'database.backup',
        'database.restore',
        'controllers.login_controller',
        'controllers.estudiante_controller',
        'controllers.matricula_controller',
        'controllers.pago_controller',
        'controllers.usuario_controller',
        'controllers.configuracion_controller',
        'controllers.categoria_controller',
        'controllers.tarifa_controller',
        'controllers.inventario_controller',
        'controllers.reporte_controller',
        'controllers.auditoria_controller',
        'controllers.importar_controller',
        'controllers.persona_controller',
        'controllers.beca_controller',
        'controllers.venta_controller',
        'controllers.egreso_controller',
        'controllers.dashboard_controller',
        'services.concepto_service',
        'services.auth_service',
        'services.estudiante_service',
        'services.matricula_service',
        'services.pago_service',
        'services.usuario_service',
        'services.configuracion_service',
        'services.categoria_service',
        'services.tarifa_service',
        'services.inventario_service',
        'services.reporte_service',
        'services.auditoria_service',
        'services.importar_service',
        'services.persona_service',
        'services.apoderado_service',
        'services.beca_service',
        'services.cuota_service',
        'services.dashboard_service',
        'services.venta_service',
        'services.egreso_service',
        'services.tipo_uniforme_service',
        'updater.update_service',
        'utils.constants',
        'utils.helpers',
        'utils.validators',
        'utils.security',
        'utils.dates',
        'utils.excel_exporter',
        'utils.excel_parser',
        'utils.csv_parser',
        'utils.logger',
        'utils.ui_helpers',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AcademiaFutbol',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(BASE_DIR, 'assets', 'icons', 'app.ico'),
    version=os.path.join(BASE_DIR, 'version.txt'),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='AcademiaFutbol',
)
